feat: WhitelistAndActiveProposalLimiter and MerkleVoting Strategies
razor-network/sx-evm pull request #1
Opened 2024-02-26 08:02 UTC by yohanelly95

- WhitelistAndActiveProposalLimiter is the Proposal Validation Strategy that we will use
   - params: 
      -  cooldownperiod
      - maxActiveProposals
 - MerkleVotingStrategy is the Voting Strategy that we will use
    - params:
      - proposalId
      Note: the proposalId for each MerkleVotingStrategy will be unique and this contract needs to be updated before creating a proposal.

2024-02-29 10:22 UTC, SamAg19 requested changes

2024-02-29 10:22 UTC, SamAg19 commented on src/voting-strategies/MerkleWhitelistVotingStrategy.sol
> +
This can be removed

2024-02-29 10:22 UTC, SamAg19 commented on src/voting-strategies/VanillaVotingStrategy.sol
> +    function updateProposalData(
This can be removed

2024-02-29 10:22 UTC, SamAg19 commented on src/voting-strategies/WhitelistVotingStrategy.sol
> +    function updateProposalData(
This can be removed

2024-02-29 10:27 UTC, yohanelly95 commented on src/voting-strategies/CompVotingStrategy.sol
> +    function updateProposalData(
Since they all use the same voting interface it throws an error, just keeping it for now in the existing voting strategies. We will not use these contracts in production @SamAg19

2024-05-27 05:15 UTC, SamAg19 approved these changes

2024-05-27 05:21 UTC, rajkharvar approved these changes

2024-05-27 05:28 UTC, merged